export default [
  {
    id: "0",
    timestamp: "January 9, 2020",
    name: "Edward Newgate",
    type0fRequest: "Barangay Clearance",
    timeOfRequest: "12:00-1:00",
    purpose: "Requirement for NBI",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "1",
    timestamp: "March 2, 2021",
    name: "Edward Newgate",
    type0fRequest: "Certificate of Residence",
    timeOfRequest: "8:00-9:00",
    purpose: "Application of credit card",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "2",
    timestamp: "July 25, 2023",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "1:00-2:00",
    purpose: "Find OnePiece",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "3",
    timestamp: "February 25, 2023",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "10:00-11:00",
    purpose: "Go to laugh tale",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "4",
    timestamp: "December 2, 2022",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "4:00-5:00",
    purpose: "for elbaf",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "5",
    timestamp: "January 9, 2020",
    name: "Edward Newgate",
    type0fRequest: "Barangay Clearance",
    timeOfRequest: "12:00-1:00",
    purpose: "Requirement for NBI",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "6",
    timestamp: "March 2, 2021",
    name: "Edward Newgate",
    type0fRequest: "Certificate of Residence",
    timeOfRequest: "8:00-9:00",
    purpose: "Application of credit card",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "7",
    timestamp: "July 25, 2023",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "1:00-2:00",
    purpose: "Find OnePiece",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "8",
    timestamp: "February 25, 2023",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "10:00-11:00",
    purpose: "Go to laugh tale",
    actionButton: "",
    requestStatus: "Pending",
  },
  {
    id: "9",
    timestamp: "December 2, 2022",
    name: "Edward Newgate",
    type0fRequest: "Barangay clearance",
    timeOfRequest: "4:00-5:00",
    purpose: "for elbaf",
    actionButton: "",
    requestStatus: "Pending",
  },
  // Add more data objects here];
];
